# config.ini
[Paths]
WEB_DRIVER_PATH     = C:/chromeDriver/chromedriver.exe
SAVE_FOLDER_FRONT   = img
SAVE_FOLDER_BACK    = img_back
EN_JA_NAME_LIST     = en_ja_name_list.txt
# Basic Land 取得用
SAVE_FOLDER_BASIC   = img_basic

[URL]
SET_TYPE    = products
SET_NAME    = avatar-the-last-airbender
CIGPRODUCT  = tla-products-arena-limited-pack
CIGSET      = ['TLA', 'TLE']
# Basic Land 取得用
PLAY_BOOSTER = tla-products-play-boosters

[Selenium]
SCROLL_PAUSE_TIME = 1
SCROLL_AMOUNT = 500